### ISSUE TITLE
Error when running scrapper

### ISSUE THREAD

**Issue by cosmergen** [1fge/matricula-online-scraper#1]
Hi when I try to run the scrapper I get the following error: 
File "main.py", line 26
    logging.error(f"{urls_file_path} Not Found, Exiting")

I attempted the URL I wanted and even tried the sample URL provided in the readme.

<img width="1239" alt="Screen Shot 2022-01-19 at 7 36 30 PM" src="https://user-images.githubusercontent.com/98067500/150246562-bfff6a91-9f35-46a6-8f95-65786e6f6a9c.png">
 
Content of my working directory.
<img width="221" alt="Screen Shot 2022-01-19 at 7 39 45 PM" src="https://user-images.githubusercontent.com/98067500/150246865-187e4efe-18e2-445a-865c-16593836aff3.png">

Any assistance you can provide would be greatly appreciated. 
MacBook Pro 2017
macOS Catalina
Python 3.10.2

**Comment by 1fge** [comment]
Hello,

It looks like you are running Python 2 when attempting to use the script. To confirm this, try `python --version` in your terminal. If that shows Python 2, make sure you have Python 3 installed and attempt to run the script again using the `python3` command.
