### ISSUE TITLE
Single page

### ISSUE THREAD

**Issue by wp4711** [1fge/matricula-online-scraper#2]
Hi, is it possible to download a single page or a page range? eg. link to the url of the page and then eg. 10 pages after that page?

**Comment by 1fge** [comment]
Hi,

Apologies for the late response. Yes, I can look to add this feature in as a separate command line argument.

**Comment by 1fge** [comment]
The most recent commit has added this feature in. 

If you do not want to download all of the images from the archive, you can now specify a range. If you want only the file from the URL, you can set the range flag to 1. If you want the next 10, you can also set the range to 10.
