### ISSUE TITLE
Matricula Online Scraper installation doesn't work

### ISSUE THREAD

**Issue by vluebben** [1fge/matricula-online-scraper#4]
I have installed Python and the required packages (beautifulsoup4, git-clone, Js2Py, requests, wheel).

But I can not install the **Matricula Online Scraper files** using: git clone https://github.com/1fge/matricula-online-scraper

Using git-clone https://github.com/1fge/matricula-online-scraper instead I get a very long error message:

![Unbenannt](https://user-images.githubusercontent.com/119100860/204078601-354b9f1c-a6b7-4cf0-8478-dafca3c150e1.png)

**Comment by 1fge** [comment]
Hi, 

If you are having issues only with running the clone operation, perhaps you can install the files from GitHub by downloading as a zip.

**Comment by vluebben** [comment]
It worked. Thanks!!!

**Comment by vluebben** [comment]
It worked. Thanks!!!
